MessyData/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^adminnn/', include(admin.site.urls)),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'',include('mainsite.urls',namespace='mainsite')),
    #url(r'^users/',include('registration.backends.hmac.urls')),
]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

mainsite/urls.py
#!/usr/bin/env Python
# coding=utf-8

from django.conf.urls import url,include
from . import views



urlpatterns = [
    #homepage
    url(r'^$',views.index,name='index'),
    #Cahrpters
    url(r'^charpters/$',views.charpters,name='charpters'),
    #Items
    url(r'^items/$',views.items,name='items'),
    #certain chapter
    url(r'^charpters/(?P<charpter_id>\d+)/$',views.charpter,name='charpter'),
    #certain item
    url(r'^items/(?P<item_id>\d+)/$',views.item,name='item'),
    #new item
    url(r'^new_item/$',views.new_item,name='new_item'),
   #new item entry
    url(r'^new_itementry/(?P<item_id>\d+)/$',views.new_itementry,name='new_itementry'),
    #edit item entry
    url(r'^edit_itementry/(?P<itementry_id>\d+)/$',views.edit_itementry,name='edit_itementry'),
   #Statistics
    url(r'^statistics/$',views.statistics,name='statistics'),
    #DesStatistics
    url(r'^statistics/desstat/$',views.desstat,name='desstat'),
    #DesStatisticsResult
    url(r'^statistics/desstat/result/$',views.result,name='result'),
    #DesStatisticsResult-boxplot
    url(r'^statistics/desstat/result/boxplot/$',views.boxplot,name='boxplot'),
    #DesStatisticsResult-hist
    url(r'^statistics/desstat/result/hist/$',views.hist,name='hist'),
    #normtest
    url(r'^statistics/normtest/$',views.normtest,name='normtest'),
    #normresult
    url(r'^statistics/normresult/$',views.normresult,name='normresult'),
    #sdtest
    url(r'^statistics/sdtest/$',views.sdtest,name='sdtest'),
    #sdtestresult
    url(r'^statistics/sdtestresult/$',views.sdtestresult,name='sdtestresult'),
    #dttest
    url(r'^statistics/dttest/$',views.dttest,name='dttest'),
    #dttestres
    url(r'^statistics/dttestres/$',views.dttestres,name='dttestres'),
    #pttest
    url(r'^statistics/pttest/$',views.pttest,name='pttest'),
    #pttestres
    url(r'^statistics/pttestres/$',views.pttestres,name='pttestres'),
    #upttest
    url(r'^statistics/upttest/$',views.upttest,name='upttest'),
    #upttestres
    url(r'^statistics/upttestres/$',views.upttestres,name='upttestres'),
    #attest
    url(r'^statistics/attest/$',views.attest,name='attest'),
    #attestres
    url(r'^statistics/attestres/$',views.attestres,name='attestres'),
    #chiq
    url(r'^statistics/chiq/$',views.chiq,name='chiq'),
    #chiqres
    url(r'^statistics/chiqres/$',views.chiqres,name='chiqres'),
    #fisher
    url(r'^statistics/fisher/$',views.fisher,name='fisher'),
    #fisherres
    url(r'^statistics/fisherres/$',views.fisherres,name='fisherres'),
    #Dataminings
    url(r'^dataminings/$',views.dataminings,name='dataminings'),
    #apdie
    url(r'^dataminings/apdie/$',views.apdie,name='apdie'),
    #apdieres
    url(r'^dataminings/apdie/apdieres/$',views.apdieres,name='apdieres'),
    #appoint
    url(r'^dataminings/appoint/$',views.appoint,name='appoint'),
    #appointres
    url(r'^dataminings/appoint/appointres/$',views.appointres,name='appointres'),
    #affinity
    url(r'^dataminings/affinity/$',views.affinity,name='affinity'),
    #affinityres
    url(r'^dataminings/affinity/affinityres/$',views.affinityres,name='affinityres'),
    #affup
    url(r'^dataminings/affup/$',views.affup,name='affup'),
    #affupres
    url(r'^dataminings/affup/affupres/$',views.affupres,name='affupres'),
    #Datalabs
    url(r'^datalabs/$',views.datalabs,name='datalabs'),
    #kNN
    url(r'^datalabs/knn/$',views.knn,name='knn'),
    #kNNtest
    url(r'^datalabs/knn/knntest$',views.knntest,name='knntest'),
    #kNNtouch
    url(r'^datalabs/knn/knntouch$',views.knntouch,name='knntouch'),
    #kNNup
    url(r'^datalabs/knnup/$',views.knnup,name='knnup'),
    #kNNupfile
    url(r'^datalabs/knnup/knnupres/$',views.knnupres,name='knnupres'),
    #id3
    url(r'^datalabs/id3/$',views.id3,name='id3'),
    #id3res
    url(r'^datalabs/id3/id3res/$',views.id3res,name='id3res'),
    #apdie
    url(r'^datalabs/apdie/$',views.apdie,name='apdie'),
    #caa
    url(r'^datalabs/caa/$',views.caa,name='caa'),
    #caares
    url(r'^datalabs/caa/caares$',views.caares,name='caares'),
    #cdna
    url(r'^datalabs/cdna/$',views.cdna,name='cdna'),
    #cdnares
    url(r'^datalabs/cdna/cdnares$',views.cdnares,name='cdnares'),
    #crna
    url(r'^datalabs/crna/$',views.crna,name='crna'),
    #crnares
    url(r'^datalabs/crna/cdnares$',views.crnares,name='crnares'),
    #wc1
    url(r'^datalabs/wc1/$',views.wc1,name='wc1'),
    #wc2
    url(r'^datalabs/wc2/$',views.wc2,name='wc2'),
    #wc2res
    url(r'^datalabs/wc2/wc2res/$',views.wc2res,name='wc2res'),
    #oner
    url(r'^datalabs/oner/$',views.oner,name='oner'),
    #onerres
    url(r'^datalabs/oner/onerres/$',views.onerres,name='onerres'),
    #onerup
    url(r'^datalabs/onerup/$',views.onerup,name='onerup'),
    #onerupres
    url(r'^datalabs/onerup/onerupres/$',views.onerupres,name='onerupres'),
    #facerec
    url(r'^datalabs/facerec/$',views.facerec,name='facerec'),
    #facerecres
    url(r'^datalabs/facerec/facerecres/$',views.facerecres,name='facerecres'),
    #brec
    url(r'^datalabs/brec/$',views.brec,name='brec'),
    #brecres
    url(r'^datalabs/brec/brecres/$',views.brecres,name='brecres'),
    #mcw
    url(r'^datalabs/mcw/$',views.mcw,name='mcw'),
    #log
    url(r'^datalabs/log/$',views.log,name='log'),
    #logres
    url(r'^datalabs/log/logres/$',views.logres,name='logres'),
    #logup
    #url(r'^datalabs/logup/$',views.logup,name='logup'),
    #logupres
    #url(r'^datalabs/logup/logupres/$',views.logupres,name='logupres'),
    #ada
    url(r'^datalabs/ada/$',views.ada,name='ada'),
    #adares
    url(r'^datalabs/ada/adares/$',views.adares,name='adares'),
    #nndl
    url(r'^datalabs/nndl/$',views.nndl,name='nndl'),
    #nndlres
    url(r'^datalabs/nndl/nndlres/$',views.nndlres,name='nndlres'),
    #4BC
    url(r'^datalabs/bc/$',views.bc,name='bc'),
    #4BCres
    url(r'^datalabs/bc/bcres/$',views.bcres,name='bcres'),
]




users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views


urlpatterns = [
    url(r'^login/$',login,{'template_name':'users/login.html'},name='login'),
	url(r'^logout/$',views.logout_view,name='logout'),
	url(r'^register/$',views.register,name='register'),
]

mainsite/forms.py
#!/usr/bin/env Python
# coding=utf-8
from django import forms
from .models import Item,itemEntry

from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError

class ItemForm(forms.ModelForm):
    class Meta:
	    model=Item
	    fields=['title']
	    labels={'title':''}


class itemEntryForm(forms.ModelForm):
    class Meta:
	    model=itemEntry
	    fields=['text']
	    labels={'text':''}
	    widgets={'text':forms.Textarea(attrs={'cols':80})}


def validate_excel(value):
    if value.name.split('.')[-1] not in ['xls','xlsx']:
        raise ValidationError(_('Invalid File Type: %(value)s'),params={'value': value},)

class UploadExcelForm(forms.Form):
    excel = forms.FileField(validators=[validate_excel]) #这里使用自定义的验证

mainsite/views.py
#!/usr/bin/env Python
# coding=utf-8
from __future__ import unicode_literals

from django.shortcuts import render

from .models import Charpter,Item,itemEntry,Statistic,DataMining,DataLab

from django.http import HttpResponseRedirect,Http404,HttpResponse


from django.core.urlresolvers import reverse

from .forms import ItemForm,itemEntryForm,UploadExcelForm

from django.contrib.auth.decorators import login_required

from django.template.loader import get_template

from numpy import mean,median,var,std,ptp
import numpy as np

import matplotlib

matplotlib.use('Agg')

from matplotlib.figure import Figure                      
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.dates import DateFormatter
import matplotlib.pyplot as plt

from scipy.stats import kstest,levene,ttest_1samp,ttest_rel,ttest_ind,chi2_contingency,fisher_exact
from .knn import *
from .biologists import *
from .apriori import *
import codecs
from . import decTree
import xlrd,copy
from django.core.files.uploadedfile import InMemoryUploadedFile

from PIL import Image,ImageDraw
from wordcloud import WordCloud, STOPWORDS
import jieba
from .affinity import *
from .oner import *
from .mcwriter import *
#from .log import *
#from .facerec import *




def index(request):
    return render(request,'mainsite/index.html')
	
def charpters(request):
    charpters=Charpter.objects.order_by('pub_date')
    context={'charpters':charpters}
    return render(request,'mainsite/charpters.html',context)

@login_required	
def items(request):
    items=Item.objects.filter(owner=request.user).order_by('pub_date')
    context={'items':items}
    return render(request,'mainsite/items.html',context)
	
def charpter(request,charpter_id):
    charpter=Charpter.objects.get(id=charpter_id)
    entries=charpter.charpterentry_set.order_by('-pub_date')
    context={'charpter':charpter,'entries':entries}
    return render(request,'mainsite/charpter.html',context)

@login_required	
def item(request,item_id):
    item=Item.objects.get(id=item_id)
    if item.owner !=request.user:
        raise Http404
    entries=item.itementry_set.order_by('-pub_date')
    context={'item':item,'entries':entries}
    return render(request,'mainsite/item.html',context)

@login_required	
def new_item(request):
    if request.method!='POST':
        form=ItemForm()
    else:
        form=ItemForm(request.POST)
        if form.is_valid():
            new_item=form.save(commit=False)
            new_item.owner=request.user
            new_item.save()
            return HttpResponseRedirect(reverse('mainsite:items'))
	
    context={'form':form}
    return render(request,'mainsite/new_item.html',context)

@login_required
def new_itementry(request,item_id):
    item=Item.objects.get(id=item_id)
    if request.method!='POST':
        form=itemEntryForm()
    else:
        form=itemEntryForm(data=request.POST)
        if form.is_valid():
            new_itementry=form.save(commit=False)
            new_itementry.item=item
            new_itementry.save()
            return HttpResponseRedirect(reverse('mainsite:item',args=[item_id]))
	
    context={'item':item,'form':form}
    return render(request,'mainsite/new_itementry.html',context)

@login_required
def edit_itementry(request,itementry_id):
    entry=itemEntry.objects.get(id=itementry_id)
    item=entry.item
    if item.owner !=request.user:
        raise Http404
    if request.method!='POST':
        form=itemEntryForm(instance=entry)
    else:
        form=itemEntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainsite:item',args=[item.id]))
	
    context={'entry':entry,'item':item,'form':form}
    return render(request,'mainsite/edit_itementry.html',context)

def statistics(request):
    statistics=Statistic.objects.order_by('pub_date')
    context={'statistics':statistics}
    return render(request,'mainsite/statistics.html',context)

def dataminings(request):
    dataminings=DataMining.objects.order_by('pub_date')
    context={'dataminings':dataminings}
    return render(request,'mainsite/dataminings.html',context)

def datalabs(request):
    datalabs=DataLab.objects.order_by('pub_date')
    context={'datalabs':datalabs}
    return render(request,'mainsite/datalabs.html',context)

def desstat(request):
    return render(request,'mainsite/desstat.html')


	
def result(request):
    
	
    form = UploadExcelForm(request.POST, request.FILES)
    if form.is_valid():
        wb = xlrd.open_workbook(filename=None, file_contents=request.FILES['excel'].read()) # 关键点在于这里
    data=[]
    table = wb.sheets()[0]#获取整个第一张表
    #col = table.ncols
    row = table.nrows
    #print col,row
    for i in range(1, row):
        col = table.row_values(i)
        data.append(col)
    datanum=[]#;print data
    for i in range(0,len(data)):
        datanum.append(data[i][0])

    total=sum(datanum)
    datamean=round(mean(datanum),3)
    datamedian=round(float(median(datanum)),3)
    datarange=round(ptp(datanum),3)
    datavar=round(var(datanum),3)
    datastd=round(std(datanum),3)
    datacv=round((datastd/datamean*100),3)
    context={'data':data,'datamean':datamean,'datamedian':datamedian,'datarange':datarange,'datavar':datavar,'datastd':datastd,'datacv':datacv}
    return render(request,'mainsite/result.html',context)



@login_required
def boxplot(request):
    form = UploadExcelForm(request.POST, request.FILES)
    if form.is_valid():
        wb = xlrd.open_workbook(filename=None, file_contents=request.FILES['excel'].read()) # 关键点在于这里
    data=[]
    table = wb.sheets()[0]#获取整个第一张表
    #col = table.ncols
    row = table.nrows
    #print col,row
    for i in range(1, row):
        col = table.row_values(i)
        data.append(col)
    datanum=[]#;print data
    for i in range(0,len(data)):
        datanum.append(data[i][0])
    fig=Figure(figsize=(6,6))
    ax=fig.add_subplot(111)
    ax.boxplot(datanum)
    canvas=FigureCanvasAgg(fig)
    response=HttpResponse(content_type='image/png')
    canvas.print_png(response)
    plt.close(fig)
    return response

@login_required	
def hist(request):
    form = UploadExcelForm(request.POST, request.FILES)
    if form.is_valid():
        wb = xlrd.open_workbook(filename=None, file_contents=request.FILES['excel'].read()) # 关键点在于这里
    data=[]
    table = wb.sheets()[0]#获取整个第一张表
    #col = table.ncols
    row = table.nrows
    #print col,row
    for i in range(1, row):
        col = table.row_values(i)
        data.append(col)
    datanum=[]#;print data
    for i in range(0,len(data)):
        datanum.append(data[i][0])
    fig=Figure(figsize=(6,6))
    ax=fig.add_subplot(111)
    ax.hist(datanum)
    
    canvas=FigureCanvasAgg(fig)
    response=HttpResponse(content_type='image/png')
    canvas.print_png(response)
    plt.close(fig)
    return response

def normtest(request):
    return render(request,'mainsite/normtest.html')
	
def normresult(request):
    form = UploadExcelForm(request.POST, request.FILES)
    if form.is_valid():
        wb = xlrd.open_workbook(filename=None, file_contents=request.FILES['excel'].read()) # 关键点在于这里
    data=[]
    table = wb.sheets()[0]#获取整个第一张表
    #col = table.ncols
    row = table.nrows
    #print col,row
    for i in range(1, row):
        col = table.row_values(i)
        data.append(col)
    datanum=[]#;print data
    for i in range(0,len(data)):
        datanum.append(data[i][0])
    res=kstest(datanum, 'norm')
    z=round(float(res[0]),4)
    p=round(float(res[1]),4)
    context={'data':data,'z':z,'p':p}
    return render(request,'mainsite/normresult.html',context)
	
def sdtest(request):
    return render(request,'mainsite/sdtest.html')
	
def sdtestresult(request):
    form = UploadExcelForm(request.POST, request.FILES)
    if form.is_valid():
        wb = xlrd.open_workbook(filename=None, file_contents=request.FILES['excel'].read()) # 关键点在于这里
    data=[]
    table = wb.sheets()[0]#获取整个第一张表
    #col = table.ncols
    row = table.nrows
    #print col,row
    for i in range(1, row):
        col = table.row_values(i)
        data.append(col)
    datanum1=[]#;print data
    for i in range(0,len(data)):
        datanum1.append(data[i][0])
    datanum2=[]#;print data
    for i in range(0,len(data)):
        datanum2.append(data[i][1])
    res=levene(datanum1,datanum2,center = 'trimmed')
    f=round(float(res[0]),4)
    p=round(float(res[1]),4)
    context={'data':data,'f':f,'p':p}
    return render(request,'mainsite/sdtestresult.html',context)
	
def knn(request):
    return render(request,'mainsite/knn.html')

@login_required
def knntest(request):
    errorCount,ds,erropercentage=datingClassTest()
    context={'erropercentage':erropercentage,'ds':ds}
    return render(request,'mainsite/knntest.html',context)

@login_required
def knntouch(request):
    requestData=request.GET.copy()
    ffMiles=requestData['hours']
    iceCream=requestData['kgs']
    percentTats=requestData['percentage']
    ffMiles1=ffMiles.encode('utf-8')
    iceCream1=iceCream.encode('utf-8')
    percentTats1=percentTats.encode('utf-8')
    res=classifyPerson(ffMiles1,iceCream1,percentTats1)
    context={'res':res,'ffMiles1':ffMiles1,'iceCream1':iceCream1,'percentTats1':percentTats1}
    return render(request,'mainsite/knntouch.html',context)
	
def dttest(request):
    return render(request,'mainsite/dttest.html')
	
def dttestres(request):
    requestData=request.GET.copy()
    data1=requestData['user_data1']
    data1=str(data1)
    datanum1=[]
    for i in data1.split(' '):
        datanum1.append(int(i))
    requestData=request.GET.copy()
    data2=requestData['user_data2']
    data2=str(data2)
    datanum2=[]
    datanum2.append(int(data2))
    res=ttest_1samp(datanum1,popmean=datanum2)
    t=round(float(res[0]),4)
    p=round(float(res[1]),4)
    context={'data1':data1,'data2':data2,'t':t,'p':p}
    return render(request,'mainsite/dttestres.html',context)
	
def pttest(request):

mainsite/templates/mainsite/affinity.html
{% extends "mainsite/base.html" %}

{% block header %}
  <h2 style='font-family:微软雅黑'>1.简单亲和性分析对针刺治疗周围性面瘫主穴搭配规律研究（示例演示）</h2><br/>
  <h4 style='font-family:宋体'><strong>注意：本演示示例不可直接应用于临床、写作或引用于论文中，自主上传数据开放后所得结果则可以。</strong></h4>

{% endblock %}

{% block content %}
<h4>原始数据：</h4>
{% load staticfiles %}
      <img src="{% static 'images/affinity.PNG' %}" /><h5>……后省略（共一百个处方）</h5>
	  <br/>
	  
	  <h3><a href="{% url 'mainsite:affinityres' %}" style='font-family:微软雅黑'>运行示例（需要注册登录）</a></h3>

 








{% endblock content %}

mainsite/templates/mainsite/cdna.html
{% extends "mainsite/base.html" %}

{% block header %}
  <h1 style='font-family:微软雅黑'>2.DNA序列中碱基频率分析</h1>
{% endblock %}

{% block content %}
<h4 style='font-family:宋体'>注意：字母大小写都行中间不间隔东西，<strong>因为不想写检查代码</strong>，不举例了。</h4>
<h3>
      <div class='container'>

<form name='my form' action="{% url 'mainsite:cdnares'   %}" method='GET'>
    <textarea name='user_data' rows=3 cols=70></textarea><br/>
    <h4><input type='submit' value='提交'>
    <input type='reset' value='清除重填'></h4>
</form>
</div>

</h3>
{% endblock content %}

mainsite/templates/mainsite/chiq.html
{% extends "mainsite/base.html" %}

{% block header %}
  <h1 style='font-family:微软雅黑'>1.四格表卡方检验</h1>
{% endblock %}

{% block content %}
<h4 style='font-family:宋体'>注意：请先确定你的数据是无序的。</h4>
<h3>
      <div class='container'>

<form name='my form' action="{% url 'mainsite:chiqres'   %}" method='GET'>
	<table border="1">
<tr>
<th></th>
<th>阳性</th>
<th>阴性</th>
</tr>
<td>第一组</td><td><textarea name='a' rows=1 cols=10></textarea></td>
<td><textarea name='b' rows=1 cols=10></textarea></td>
</tr>
<tr>
<td>第二组</td><td><textarea name='c' rows=1 cols=10></textarea></td>
<td><textarea name='d' rows=1 cols=10></textarea></td>
</tr>
</table>
    <h4><input type='submit' value='提交'>
    <input type='reset' value='清除重填'></h4>
</form>
</div> 

</h3>
{% endblock content %}

mainsite/templates/mainsite/datalabs.html
{% extends "mainsite/base.html" %}

{% block header %}
  <h1 style='font-family:微软雅黑'>Data-Lab</h1>
{% endblock %}

{% block content %}
 
<h3>
      <p>一、机器学习</p>
	  <p style='font-family:微软雅黑'>（一）、kNN算法</p>
	  <h4><a href="{% url 'mainsite:knn'   %}" style='font-family:宋体'>1.通过kNN（k-近领算法）让计算机从以往数据中学习并预测中风后的疗效等级（示例演示）</a></h4>
	  <h4><a href="{% url 'mainsite:knnup'   %}"  style='font-family:宋体'>2.提交你的数据进行学习预测</a></h4><br/>
	  <h3 style='font-family:微软雅黑'><p>（二）、ID3决策树</p></h3>
	  <h4><a href="{% url 'mainsite:id3'   %}" style='font-family:宋体'>1.通过ID3决策树对名老中医治疗感冒君药选择规律研究（示例演示）</a></h4>
	  <h4 style='font-family:宋体'>2.上传你的数据进行学习预测（暂无条件开放）</h4><br/>
	  <h3 style='font-family:微软雅黑'><p>（三）、简单却极有效率的单规则分类器（OneR）</p></h3>
	  <h4><a href="{% url 'mainsite:oner' %}" style='font-family:宋体'>1.卒中住院患者<strong>死亡危险因素</strong>分析（示例演示）</a></h4>
	  <h4><a href="{% url 'mainsite:onerup' %}" style='font-family:宋体'>2.自主数据提交分析</a></h4><br/>
	  <h3 style='font-family:微软雅黑'><p>（四）、图像识别</p></h3>
	  <h4><a href="{% url 'mainsite:facerec' %}" style='font-family:宋体'>1.支持向量机图片识别示例——人脸识别</a></h4>
	  <h4><a href="{% url 'mainsite:brec' %}" style='font-family:宋体'>2.识别鉴定脑出血和脑梗塞的CT影像</a></h4>
	  <h4 style='font-family:宋体'>2.医学图像提交分析（暂无条件开放）</h4>
	  <h4><a href="{% url 'mainsite:nndl' %}" style='font-family:宋体'>4.（简单神经网络+随机梯度下降+逆向传播）手写识别的一部分，中文数据太大扯不上来，装不下，只做一个示例，手写数字识别</a></h4><br/>
	  <h3 style='font-family:微软雅黑'><p>（五）、逻辑回归</p></h3>
	  <h4><a href="{% url 'mainsite:log' %}" style='font-family:宋体'>1.逻辑回归结合随机梯度上升算法在某病病人最终结局的分析和预测（数据集中包含30%的缺失值）示例</a></h4>
	  <h4 style='font-family:宋体'>2.提交你的数据进行学习预测（暂无条件开放）</a></h4><br/>
	  <h3 style='font-family:微软雅黑'><p>（六）、Adaboost算法</p></h3>
	  <h4><a href="{% url 'mainsite:ada' %}" style='font-family:宋体'>1.运用Adaboost（Adaptive Boosting）在某病病人最终结局的分析和预测（数据集中包含30%的缺失值）示例</a></h4>
	  <h4 style='font-family:宋体'>2.提交你的数据进行学习预测（暂无条件开放）</a></h4><br/>
	  <h3 style='font-family:微软雅黑'><p>（七）、分类器在连续型数据中的比较</p></h3>
	  <h4><a href="{% url 'mainsite:bc' %}" style='font-family:宋体'>1.乳腺肿瘤细胞病例数据识别：基于四种分类器示例</a></h4><br/>
	  <h3>二、科研利器</h3>
	  <h4><a href="{% url 'mainsite:caa'   %}" style='font-family:宋体'>1.计算蛋白质序列中的氨基酸频率</a></h4>
	  <h4><a href="{% url 'mainsite:cdna'   %}" style='font-family:宋体'>2.DNA序列中碱基频率分析</a></h4>
	  <h4><a href="{% url 'mainsite:crna'   %}" style='font-family:宋体'>3.RNA序列中碱基频率分析</a></h4><br/>
	  <h3>三、有趣的玩意儿</h3>
	  <h4><a href="{% url 'mainsite:wc1'   %}" style='font-family:宋体'>1.伤寒论词云示例</a></h4>
	  <h4><a href="{% url 'mainsite:wc2'   %}" style='font-family:宋体'>2.生成你的词云</a></h4>
	  <h4><a href="{% url 'mainsite:mcw'   %}" style='font-family:宋体'>3.基于马尔可夫模型随机生成一段黄帝内经</a></h4>

	  
</h3>
{% endblock content %}


mainsite/templates/mainsite/item.html
{% extends "mainsite/base.html" %}

{% block header %}
  <h2 style='font-family:微软雅黑'>{{ item }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'mainsite:new_itementry' item.id %}" style='font-family:微软雅黑'>撰写项目计划内容</a>
  </p>

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.pub_date|date:'Y m d H:i' }}
          <small>
            <a href="{% url 'mainsite:edit_itementry' entry.id %}">
              编辑内容</a>
          </small>
        </h3>
      </div>
      <div class="panel-body" style='font-family:宋体'>
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
  {% empty %}
    还没有撰写项目计划内容
  {% endfor %}

{% endblock content %}